# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGpCOUpaEyH2H0SIVh7IOlKMN4CCUYvw
"""

from hospital_decision_support import predict_patient

if st.button("Predict"):

    result = predict_patient(
        age,
        gender,
        department,
        diagnosis
    )

    st.success(
        f"Expected Hospital Stay: {result['Hospital Stay']}"
    )

    st.info(
        f"Expected Treatment: {result['Treatment']}"
    )

    st.warning(
        f"Expected Medical Bill: {result['Medical Bill']}"
    )