# -*- coding: utf-8 -*-
"""hospital_decision_support.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkyYpAoXa9wreVV-u5pCRrzOvxW18w8l
"""

# HOSPITAL DECISION SUPPORT MODULE


import pandas as pd
import joblib



# LOAD MODELS


stay_model = joblib.load(
    "models/stay_model.joblib"
)

treatment_model = joblib.load(
    "models/treatment_model.joblib"
)

bill_model = joblib.load(
    "models/bill_model.joblib"
)



# LOAD ENCODERS


gender_encoder = joblib.load(
    "models/gender_encoder.joblib"
)

department_encoder = joblib.load(
    "models/department_encoder.joblib"
)

diagnosis_encoder = joblib.load(
    "models/diagnosis_encoder.joblib"
)


stay_encoder = joblib.load(
    "models/stay_encoder.joblib"
)

treatment_encoder = joblib.load(
    "models/treatment_encoder.joblib"
)

bill_encoder = joblib.load(
    "models/bill_encoder.joblib"
)



# PREDICTION FUNCTION


def predict_patient(age, gender, department, diagnosis):

    # Encode inputs
    gender_value = gender_encoder.transform([gender])[0]

    department_value = department_encoder.transform([department])[0]

    diagnosis_value = diagnosis_encoder.transform([diagnosis])[0]

    # Create DataFrame
    patient = pd.DataFrame({

        "Age": [age],
        "Gender": [gender_value],
        "Department": [department_value],
        "Diagnosis": [diagnosis_value]

    })

    # Make predictions
    stay_prediction = stay_model.predict(patient)

    treatment_prediction = treatment_model.predict(patient)

    bill_prediction = bill_model.predict(patient)

    # Convert predictions back to labels
    stay_result = stay_encoder.inverse_transform(
        stay_prediction
    )[0]

    treatment_result = treatment_encoder.inverse_transform(
        treatment_prediction
    )[0]

    bill_result = bill_encoder.inverse_transform(
        bill_prediction
    )[0]

    # Return results
    return {
        "Hospital Stay": stay_result,
        "Treatment": treatment_result,
        "Medical Bill": bill_result
    }